import { ScreenSize } from "@/components/sharedui/screenSize";
import "@/styles/globals.css";
import { Inter } from "next/font/google";
import { StandartLayout } from "@/components/template/standart.layout";
import { Providers } from "@/components/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <StandartLayout>{children}</StandartLayout>
        </Providers>
      </body>
    </html>
  );
}
